version: "3.8"

services:
  wisdomcircle_client:
    build:
      context: ./client
    container_name: wisdomcircle_client
    ports:
      - "29172:29172"
    volumes:
      - ./client:/app
    depends_on:
      - wisdomcircle_server
    command: npm run start
    environment:
      - REACT_APP_API

  wisdomcircle_server:
    build:
      context: ./server
    container_name: wisdomcircle_server
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    networks:
      - wisdomcircle
    command: npm run start:dev
    environment:
      - API_SERVER_PORT
      - API_MONGODB_URI
      - API_JWT_SECRET
      - API_TWILIO_ACCOUNT_SID
      - API_TWILIO_AUTH_TOKEN
      - API_TWILIO_PHONE_NUMBER
      - API_SENDGRID_API_KEY
      - API_SENDGRID_SENDER_EMAIL

  mongo:
    image: mongo:4.4-rc
    container_name: wisdomcircle_mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - wisdomcircle

networks:
  wisdomcircle:

volumes:
  mongodb:
    driver: local
